### PR TITLE
Common bugs in app

### LINKED ISSUE #143: Loader issue when user first vist sosinc app
When the user go to https://app.sosinc.io/
A message is displayed as **Logging in**
Instead it should show the **loader** of sosinc app

### LINKED ISSUE #144: Tooltip placement is bit to the right of alert icon
Whenever there is an error 
then the arrow of the validation message
should be on the tip of validation Icon. 

Right now its position is slight right to the validation  icon.

### PR DESCRIPTION
**Pull request by jkhabra**
Resolves #143 and Resolves #144

### CODE REVIEW

File: ui/src/components/Feedback/index.tsx [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+const c = classNames.bind(style);
+
+const FeedbackForm: React.FC<FormikProps<FeedbackFormValues>> = (p) => {
+  return (
+    <div className={c('container')}>
+      <form className={c('form')} onSubmit={p.handleSubmit}>
+        <div className={c('title-container')}>
+          <h2>Feedback</h2>
+          <span className={c('sub-title')}>
+            Send your complains, suggestions, or feature requests
```
Comment (bitspook) [inline ui/src/components/Feedback/index.tsx]: Typo; complains should be spelled `complaints`

File: ui/src/components/Feedback/index.tsx [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+  description: string;
+  email: string;
+  first_name: string;
+  last_name: string;
+}
+
+const validationSchema = Yup.object().shape({
+  description: Yup.string()
+    .min(2, 'Must be 2 characters or more')
+    .max(50, 'Must be 50 characters or less')
```
Comment (bitspook) [inline ui/src/components/Feedback/index.tsx]: Description should have a bigger limit. 50 characters are too little for a feedback description. Let's make it 500.

File: ui/src/components/Teams/Create/index.tsx [hunk 3]
```diff
@@ -172,7 +172,7 @@ const TeamMembers = (p: { team: Team; employees: Employee[]; isFetchingEmployees
 
     if (!member) {
       // tslint:disable-next-line:no-console
-      console.warn('Failed to add employee');
+      // console.warn('Failed to add employee');
```
Comment (bitspook) [inline ui/src/components/Teams/Create/index.tsx]: Please don't leave dead code behind. Better to just remove it.

**Review by bitspook — CHANGES_REQUESTED** [review]

**Review by bitspook — APPROVED** [review]
