### PR TITLE
Fix add daily task broken link

### LINKED ISSUE #161: Not able to add Status on dashboard
Hey 

I am not able to add status in the [dashboard](https://app.sosinc.io/dashboard).

The button press does nothing and there is no error in the console as well. Can you pl guide me what I am doing wrong here. 

Thanks

### PR DESCRIPTION
**Pull request by jkhabra**
Resolves #161

- fix reset-password pop design 
- fix delete employee bug

### CODE REVIEW

File: ui/src/components/Tasks/DailyTasks/index.tsx [hunk 1]
```diff
@@ -64,13 +64,14 @@ const selectMoreOptions = [
 ];
 
 // const NoTodaysCommitment: React.FC<{ addItemCb: () => void }> = (p) => (
-const NoTodaysCommitment = () => (
+const NoTodaysCommitment: React.FC<{ openSlidebar: () => void }> = (p) => (
```
Comment (bitspook) [inline ui/src/components/Tasks/DailyTasks/index.tsx]: Callback props should be named with `on` prefix. This should be called `onOpenSlidebar`. But a better name here can probably be `onAddCommitment`. 
It's better if we communicate the intention of the action instead of what the UI is going to look like. There is a good chance that we'll change the UI at some point, e.g it might become something which is not opening a slidebar, but a popup instead.

File: ui/src/components/Tasks/DailyTasks/index.tsx [hunk 2]
```diff
@@ -64,13 +64,14 @@ const selectMoreOptions = [
...
   <div className={c('not-found-container')}>
     <NoItemsFound
       Icon={RiPlayListAddLine}
       message=" You haven't added a status update for today."
       addItemText="Add one"
       addItemUrl=""
+      addItemCb={() => p.openSlidebar()}
```
Comment (bitspook) [inline ui/src/components/Tasks/DailyTasks/index.tsx]: Since no arguments are needed for the called function, we can simply do:
```suggestion
      addItemCb={p.openSlidebar}
```

File: ui/src/components/Tasks/DailyTasks/index.tsx [hunk 3]
```diff
@@ -296,7 +297,7 @@ const DailyTaskRow: React.FC<DailyTask & { isFetching: boolean }> = ({ isFetchin
   );
 };
 
-const DailyTasks: React.FC = () => {
+const DailyTasks: React.FC<{ openSlidebar: () => void }> = (p) => {
```
Comment (bitspook) [inline ui/src/components/Tasks/DailyTasks/index.tsx]: Same as above comments.

**Review by bitspook — CHANGES_REQUESTED** [review]

**Review by bitspook — APPROVED** [review]
